image: maven:3.8.6-eclipse-temurin-17

stages:
  - test
  - report

variables:
  MAVEN_CLI_OPTS: "-B -Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

before_script:
  - echo "Using Java version:"
  - java -version
  - echo "Using Maven version:"
  - mvn -version

test:
  stage: test
  script:
    - mvn clean verify
  artifacts:
    paths:
      - target/site/serenity
    expire_in: 1 week

report:
  stage: report
  script:
    - mvn serenity:aggregate
  artifacts:
    paths:
      - target/site/serenity/index.html
    expire_in: 1 week