name: Serenity BDD Tests

on:
  push:
    branches: [ '*' ]  # Se ejecuta en cualquier rama al hacer push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Run Serenity tests
        run: mvn clean verify -Dwebdriver.headless.mode=true

      - name: Upload Serenity report
        uses: actions/upload-artifact@v3
        if: always()  # Sube el reporte aunque falle el test
        with:
          name: serenity-report
          path: target/site/serenity